version: '3.8'

services:
  php:
    build:
      context: .
    image: yii2app-custom
    ports:
      - '8000:80'
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - yii2app-data:/var/www/html  # Named volume, safe in Swarm

volumes:
  yii2app-data:

networks:
  app-net:
    driver: overlay

