version: '3.8'

services:
  yii2-app:
  image: croodycoder/yii2-app:latest
  ports:
    - "8080:80"

  deploy:
    replicas: 1
    restart_policy:
      condition: on-failure

    networks:
      - app-network

networks:
  app-network:
    driver: overlay