---
- name: Configure NGINX Reverse Proxy for Yii2 App
  hosts: all
  become: true

  tasks:
    - name: Create reverse proxy NGINX config
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name  localhost;

              location / {
                  proxy_pass http://localhost:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Reload NGINX
      systemd:
        name: nginx
        state: reloaded
